version: '3.8'

services:
  app:
    build: .
    container_name: quizlet_app
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGODB_URI=mongodb://mongodb:27017/quizlet-flashcard-generator
      - JWT_SECRET=docker_compose_secret_replace_in_production
      - JWT_LIFETIME=1d
      - API_PREFIX=/api/v1
      - RATE_LIMIT_WINDOW_MS=900000
      - RATE_LIMIT_MAX=100
      - MAX_FILE_SIZE_MB=50
      - LOG_LEVEL=info
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - quizlet-network

  mongodb:
    image: mongo:latest
    container_name: quizlet_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped
    networks:
      - quizlet-network
    command: mongod --logpath=/dev/null # Disable logging to reduce disk usage

networks:
  quizlet-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local 