[build]
  base = "client/"
  publish = "dist/"
  command = "npm run build"

# Handle SPA routing (client-side routing)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environmental variables for production
[context.production.environment]
  VITE_NODE_ENV = "production"
  # This will need to be updated to your actual backend API URL when deployed
  VITE_API_URL = "https://your-backend-api-url.render.com/api"

# Environmental variables for development branches
[context.branch-deploy.environment]
  VITE_NODE_ENV = "development"
  VITE_API_URL = "https://dev-your-backend-api-url.render.com/api"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; img-src 'self' data:; style-src 'self' 'unsafe-inline'; script-src 'self'; connect-src 'self' https://your-backend-api-url.render.com;" 