services:
  # Web Service for the Quizlet Flashcard Generator
  - type: web
    name: quizlet-flashcard-api
    env: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5001
      - key: API_PREFIX
        value: /api/v1
      - key: ALLOWED_ORIGINS
        value: https://lustrous-tartufo-9102a1.netlify.app,http://localhost:3000,http://localhost:5173,*
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_LIFETIME
        value: 1d
      - key: MONGODB_URI
        sync: false # Add this manually in the dashboard
      - key: RATE_LIMIT_WINDOW_MS
        value: 900000
      - key: RATE_LIMIT_MAX
        value: 100
      - key: MAX_FILE_SIZE_MB
        value: 50
      - key: LOG_LEVEL
        value: info
    healthCheckPath: /health
    autoDeploy: true
  - type: web
    name: quizlet-flashcard-generator
    runtime: node
    plan: free # Using the free tier
    buildCommand: node ./build.js
    startCommand: node server.js
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: quizlet-flashcard-generator
          envVarKey: PORT
      - key: MONGODB_URI
        sync: false # This will be set manually in the Render dashboard
      - key: JWT_SECRET
        generateValue: true # Automatically generate a secure random value
      - key: JWT_LIFETIME
        value: 1d
      - key: API_PREFIX
        value: /api/v1
      - key: RATE_LIMIT_WINDOW_MS
        value: 900000
      - key: RATE_LIMIT_MAX
        value: 100
      - key: MAX_FILE_SIZE_MB
        value: 50
      - key: LOG_LEVEL
        value: info 